environment:
  nodejs_version: "13"
  github_access_token:
    secure: HB3n97DnnVDsHgE4+O//U0IBTFfmNnba1yUYKL9BIxKskTLjG1JgjCxcOw5bt2IE
  github_email:
    secure: f4ZbxJpYFukw1vWtRf/S8DYXUIOTUN5FYN+ZXjsnA/He32jbxIFKYUXw99VhvmR4
branches:
  only:
    - master
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - git config --global user.name "AppVeyor"
  - git config --global user.email $env:github_email
  - git restore package.json
  - npm run deploy
test: off
build: off